/**
 * Arrowfish Wiki — i18n language switcher
 * Supports ZH (default) and EN. Persists choice to localStorage key 'aw_lang'.
 * Usage: add data-i18n="key" to any element. Call initLang() on DOMContentLoaded.
 */

const T = {
  zh: {
    /* ── Index page ── */
    'logo.tag':          'Internal',
    'hero.title':        '团队内部文档中心',
    'hero.sub':          '产品说明、质量保证手册、项目演进故事——所有核心文档集中在这里',
    'filter.all':        '全部',
    'filter.prd':        'PRD',
    'filter.qa':         'QA',
    'filter.story':      'Story',
    'filter.dev':        'Dev',
    'filter.ba':         'BA',
    'filter.ops':        'Ops',
    'section.docs':      '文档列表',
    'card.prd.title':    'Arrowfish VPN 业务说明文档',
    'card.prd.desc':     '产品功能全貌、用户体系、套餐与支付、VPN连接机制、营销与内容模块的完整业务逻辑说明。BA / PM 产品上手必读。',
    'card.prd.audience': '适合：BA · PM · 非技术成员',
    'card.story.title':  '从 Arrowfish 到 FFF — 产品演进故事',
    'card.story.desc':   '为什么我们决定重建一款全新应用？Arrowfish 的现状、局限、FFF 的目标和时间线，帮助所有人理解项目方向。',
    'card.story.audience':'适合：全体团队成员',
    'card.qa.title':     'QA 测试手册 — v3.7.0 测试环境配置',
    'card.qa.desc':      'Staging 测试基线（v3.7.0 当前生产版）配置一览：登录规则、免费时长、VPN 连接行为、版本控制、支付说明、节点同步及常见误判对照。',
    'card.qa.audience':  '适合：QA 测试人员',
    'card.dev.title':    '开发者上手手册 — Claude Sprint 流程',
    'card.dev.desc':     '6 阶段任务流程（领取 → 计划 → 执行 → 验证 → 提交 → 收尾）、Lead vs Dev 角色分工、Sprint 影响升级路径、Claude 技能速查。团队统一标准，新成员上手必读。',
    'card.dev.audience': '适合：开发团队（全体）',
    'card.ops.title':    '节点运维手册 — 生命周期与自动化',
    'card.ops.desc':     '从节点采购到退役的全流程：健康状态机、自动下线/恢复、DNS 自动化（GoDaddy + Cloudflare）、后台一键开通 / Format、Telegram 告警规则、部署 SOP。',
    'card.ops.audience': '适合：开发团队 · 运维',
    'card.ba.title':     'BA 业务分析手册 — 数据 · 流程 · 后台',
    'card.ba.desc':      '用户漏斗、关键指标、付费套餐 / 专线流程、退款与客服升级、抽奖 / 优惠券机制、后台常用操作。BA 与运营日常工作的速查手册。',
    'card.ba.audience':  '适合：BA · 运营 · 客服',
    'card.read':         '阅读文档',
    'footer':            'Arrowfish Team · 内部文档 · 请勿对外分享 · 2026',

    /* ── Doc page chrome ── */
    'doc.back':          '返回文档中心',
    'doc.toc.label':     '目录',
    'doc.toc.toggle':    '目录',

    /* ── PRD TOC ── */
    'prd.toc.s1':  '一、产品是什么',
    'prd.toc.s2':  '二、产品战略方向',
    'prd.toc.s3':  '三、用户体系',
    'prd.toc.s4':  '四、会员套餐',
    'prd.toc.s5':  '五、支付方式',
    'prd.toc.s6':  '六、VPN 连接功能',
    'prd.toc.s7':  '七、免费体验与广告',
    'prd.toc.s8':  '八、积分与抽奖',
    'prd.toc.s9':  '九、推荐与佣金',
    'prd.toc.s10': '十、优惠券',
    'prd.toc.s11': '十一、营销与活动',
    'prd.toc.s12': '十二、内容模块',
    'prd.toc.s13': '十三、反馈与客服',
    'prd.toc.s14': '十四、消息通知',
    'prd.toc.s15': '十五、管理后台',
    'prd.toc.s16': '十六、合规与隐私',
    'prd.toc.s17': '十七、业务数据',

    /* ── Story TOC ── */
    'story.toc.s1': '背景：我们从哪里接手',
    'story.toc.s2': 'Arrowfish 的现状',
    'story.toc.s3': '为什么需要 FFF',
    'story.toc.s4': 'FFF 是什么',
    'story.toc.s5': '两个产品如何并存',
    'story.toc.s6': '里程碑时间线',
    'story.toc.s7': '对团队意味着什么',
    'story.toc.s8': '关键风险',

    /* ── QA TOC ── */
    'qa.toc.s1':  '测试环境基本信息',
    'qa.toc.s2':  '登录与账号安全',
    'qa.toc.s3':  '免费用户时长限制',
    'qa.toc.s4':  'VPN 连接行为（v3.6.x 重连特性）',
    'qa.toc.s5':  '客户端版本控制',
    'qa.toc.s6':  '系统功能开关',
    'qa.toc.s7':  '广告配置',
    'qa.toc.s8':  '支付功能（含 IAP 续订）',
    'qa.toc.s9':  '节点同步机制（含一键开通 / Format）',
    'qa.toc.s10': '常见误判对照表',
    'qa.toc.s11': '已知问题清单',
    'qa.toc.s12': '测试账号管理',
    'qa.toc.s13': '测试 vs 生产差异',
    'qa.toc.s14': '最近发布变更（v3.7.0 / v3.2.0 上线）',
    'qa.toc.s15': '4 渠道下载站验证流程',

    /* ── BA TOC ── */
    'ba.toc.s1':  '用户漏斗与关键指标',
    'ba.toc.s2':  '会员套餐与定价',
    'ba.toc.s3':  '专线 / 专属 IP 工作流',
    'ba.toc.s4':  '支付通道与对账',
    'ba.toc.s5':  '退款与客服升级',
    'ba.toc.s6':  '抽奖 · 优惠券 · 推荐机制',
    'ba.toc.s7':  '节点与线路（业务侧）',
    'ba.toc.s8':  '后台常用操作速查',
    'ba.toc.s9':  '客户端与冻结版本',
    'ba.toc.s10': '术语对照表',

    /* ── Dev onboarding ── */
    'dev.badge':       'Developer',
    'dev.title':       '开发者上手手册 — 使用 Claude 完成 Sprint 任务的标准流程',
    'dev.meta.audience':'适合：全体开发者（新加入与资深）',
    'dev.toc.s1':  '一、首次配置',
    'dev.toc.s2':  '二、每日开始工作',
    'dev.toc.s3':  '三、6 阶段任务流程',
    'dev.toc.s4':  '四、Phase 1 — 领取任务',
    'dev.toc.s5':  '五、Phase 2 — 计划',
    'dev.toc.s6':  '六、Phase 3 — 执行',
    'dev.toc.s7':  '七、Phase 4 — 验证',
    'dev.toc.s8':  '八、Phase 5 — 提交',
    'dev.toc.s9':  '九、Phase 6 — 收尾',
    'dev.toc.s10': '十、角色分工',
    'dev.toc.s11': '十一、日常铁律',
    'dev.toc.s12': '十二、出问题怎么办',
    'dev.toc.s13': '十三、文件位置速查',
    'dev.toc.s14': '十四、Claude 技能速查',
    'dev.toc.s15': '十五、详细教学（每个技能怎么用）',
    'dev.toc.s16': '十六、团队改进建议通道',
    'dev.intro':   '每个开发者都按同样的 6 阶段流程完成每个任务。读一遍、书签保存、每次都按这个流程做。小团队要能"克隆"标准动作，就靠这份文档。',
    'dev.s1.h':  '一、首次配置（仅一次）',
    'dev.s1.1':  '把 5 个团队仓库克隆到 <code>~/Documents/GitLab/skytree/</code>：<code>orebackend</code> · <code>proxy_android2</code> · <code>flutter_vpn</code> · <code>vpn-internal-reports</code> · <code>.vscode</code>',
    'dev.s1.2':  '设置 Git 身份：<code>git config --global user.name "&lt;你的 GitLab 用户名&gt;"</code> + <code>git config --global user.email "&lt;你的邮箱&gt;"</code>',
    'dev.s1.3':  '安装 Claude Code CLI，从工作区根目录打开：<code>cd ~/Documents/GitLab/skytree &amp;&amp; claude</code>',
    'dev.s1.4':  '首次会话运行 <code>/start</code>——查看项目结构和当前 Sprint 状态',
    'dev.s1.5':  '读一次：<code>vpn-internal-reports/team-workflow-briefing.md</code>（完整简报）',
    'dev.s2.h':  '二、每日开始工作',
    'dev.s2.1':  '每个仓库 <code>git pull</code>',
    'dev.s2.2':  '从工作区根目录打开 Claude',
    'dev.s2.3':  '重命名会话：<code>/rename "&lt;任务简称&gt;"</code>',
    'dev.s2.4':  '打开 <code>vpn-internal-reports/Sprint-&lt;N&gt;/README.md</code> 查看 Sprint 状态',
    'dev.s3.h':  '三、6 阶段任务流程',
    'dev.s3.diagram': '┌──────────────────────────────────────────────────┐\n│  每个任务 = 一个 6 阶段循环                      │\n├──────────────────────────────────────────────────┤\n│                                                  │\n│  1. CLAIM    — 从 Sprint 计划中领取未认领任务    │\n│                                                  │\n│  2. PLAN     — /plan  （学习 + 设计 + Sprint 影响检查）│\n│                  ↳ 如超出 Sprint 容量 → 升级给 Lead│\n│                                                  │\n│  3. EXECUTE  — /plan execute                     │\n│                                                  │\n│  4. VERIFY   — /go-specialist 或 /kotlin-specialist│\n│                （只在最终 diff 上运行一次）      │\n│                                                  │\n│  5. COMMIT   — /commit                           │\n│                                                  │\n│  6. CLOSE    — /knowledge-base-updater（如有新发现）│\n│                /report update                    │\n│                /clear                            │\n│                                                  │\n└──────────────────────────────────────────────────┘',
    'dev.s4.h':  '四、Phase 1 — 领取任务（CLAIM）',
    'dev.s4.1':  '在 Sprint README 里找一个未认领、符合你优先级和技术栈的任务',
    'dev.s4.2':  '把该任务的 <code>Owner</code> 改为你的名字，<code>Status</code> 改为 <code>in-progress</code>',
    'dev.s4.3':  '从 <code>main</code> 切出分支，前缀按 <code>rules/general/git.md</code>：<code>fea/</code> 新功能 · <code>enh/</code> 优化 · <code>fix/</code> 修复 · <code>ref/</code> 重构 · <code>hot/</code> 紧急修复',
    'dev.s4.4':  '示例：<code>fix/vpn-kill-switch-doze</code>',
    'dev.s5.h':  '五、Phase 2 — 计划（PLAN）',
    'dev.s5.1':  '运行 <code>/plan</code>——进入计划模式',
    'dev.s5.2':  '让 Claude 探索代码；它问什么问题就如实回答',
    'dev.s5.3':  '把模板 <code>templates/task-plan.template.md</code> 复制到 <code>plans/&lt;分支名&gt;.md</code>',
    'dev.s5.4':  '填写：背景 · 验收标准 · 方法 · 关键文件 · 风险 · 验证方式 · 不在本次范围 · Sprint 影响',
    'dev.s5.escalate':'<strong>如果 Sprint 影响评估为"超出 Sprint 容量"：</strong>在计划文件加 <code>## SPRINT IMPACT</code> 章节，写清楚需要多几天 + 可替换任务候选。<strong>停下来，不要 ExitPlanMode。</strong>在群里告诉 Lead：<code>@lead sprint impact on Task #&lt;N&gt; — +&lt;X&gt;d. Cut-queue: Task #&lt;Y&gt;. Plan at vpn-internal-reports/plans/&lt;file&gt;.md</code>。等 Lead 决策后再继续——绝不自行扩大范围。',
    'dev.s6.h':  '六、Phase 3 — 执行（EXECUTE）',
    'dev.s6.1':  '运行 <code>/plan execute</code>——Claude 按计划一步步执行',
    'dev.s6.2':  '<strong>执行期间不要调用其他技能</strong>——让 <code>/plan execute</code> 跑完',
    'dev.s6.3':  '出现意外情况 → 停下问 Lead，不要偷偷改方向',
    'dev.s7.h':  '七、Phase 4 — 验证（VERIFY）',
    'dev.s7.p':  '只有当 diff 最终完成、准备提交时才运行。',
    'dev.s7.th.stack':'技术栈',
    'dev.s7.th.skill':'验证技能',
    'dev.s7.td.cross':'跨多栈',
    'dev.s7.1':  '修复 specialist 指出的问题',
    'dev.s7.2':  '<strong>Specialist 只跑一次</strong>——不是聊天工具，是检查点',
    'dev.s8.h':  '八、Phase 5 — 提交（COMMIT）',
    'dev.s8.1':  '运行 <code>/commit</code>',
    'dev.s8.2':  '审阅起草的提交信息，批准或调整',
    'dev.s8.3':  '标题格式：<code>Add | Fix | Update | Remove | Improve &lt;简短描述&gt;</code>（≤72 字符）',
    'dev.s8.4':  '<strong>绝对不要</strong>用 <code>--amend</code>、<code>--no-verify</code>、<code>Co-Authored-By</code>',
    'dev.s8.5':  'Hook 失败？修根因 → <strong>新建</strong>提交（不要 amend）',
    'dev.s9.h':  '九、Phase 6 — 收尾（CLOSE）',
    'dev.s9.1':  '<strong>知识库</strong>（仅当有非显然的新发现）：<code>/knowledge-base-updater "save: &lt;一句话发现&gt;"</code>。常规工作跳过。',
    'dev.s9.2':  '<strong>执行报告</strong>（每次必做）：复制 <code>templates/execution-report-entry.template.md</code>，追加到 <code>Sprint-&lt;N&gt;/execution-reports/phase-&lt;name&gt;.md</code>。填写：完成了什么 · 非显然发现 · 后续任务 · Sprint 影响。',
    'dev.s9.3':  '<strong>更新 Sprint README</strong>：把你任务的 <code>Status</code> 改为 <code>done</code>，提交到 vpn-internal-reports。',
    'dev.s9.4':  '在产品仓库发起 MR，指派 Lead 审核。',
    'dev.s9.5':  '<code>/clear</code>——释放上下文，任务结束。',
    'dev.s10.h': '十、角色分工（Lead 与 Dev）',
    'dev.s10.th.action':'动作',
    'dev.s10.r1': '添加任务到 Sprint 计划',
    'dev.s10.r1d':'❌（群里请求 Lead）',
    'dev.s10.r2': '设置优先级 / 估计天数',
    'dev.s10.r3': '认领未分配任务',
    'dev.s10.r3l':'✅（如亲自编码）',
    'dev.s10.r4': '填写任务计划（验收标准/方法/风险）',
    'dev.s10.r5': '执行 + 提交 + 推送',
    'dev.s10.r6': '决定 cut-queue / 延期',
    'dev.s10.r6d':'❌（升级）',
    'dev.s10.r7': '审核 MR',
    'dev.s10.r8': '写执行报告条目',
    'dev.s10.r9': '更新 Sprint README 状态',
    'dev.s10.r9d':'✅（仅自己的行）',
    'dev.s11.h': '十一、日常铁律（永远不要破坏）',
    'dev.s11.1': '<strong>一次一个技能</strong>——不要把 <code>/plan</code> + <code>/plan execute</code> + <code>/commit</code> 堆在一起',
    'dev.s11.2': '<strong>一个会话 = 一个任务</strong>——任务之间 <code>/clear</code>',
    'dev.s11.3': '<strong>不准自行扩大范围</strong>——发现任务变大了，升级给 Lead',
    'dev.s11.4': '<strong>Specialist 仅 Phase 4</strong>——不是"帮我看看方案"的聊天工具',
    'dev.s11.5': '<strong>永远用模板</strong>——task-plan 和 execution-report 模板，不要自由发挥',
    'dev.s11.6': '<strong>一任务一 MR</strong>——Lead 审核通过才合并',
    'dev.s12.h': '十二、出问题怎么办',
    'dev.s12.th.issue':'情况',
    'dev.s12.th.fix':  '处理方式',
    'dev.s12.r1': 'Build 失败',
    'dev.s12.r1f':'当前会话修复，重新跑 specialist，修好才能提交',
    'dev.s12.r2': '提交 hook 阻止',
    'dev.s12.r2f':'修根因，<strong>新建</strong>提交，永远不用 <code>--no-verify</code>',
    'dev.s12.r3': 'Merge 冲突',
    'dev.s12.r3f':'本地解决，在解决后的 diff 上重新跑 specialist',
    'dev.s12.r4': '远程有新提交',
    'dev.s12.r4f':'<code>git stash -u</code> → <code>git pull --ff-only</code> → <code>git stash pop</code> → 重新 build',
    'dev.s12.r5': '会话乱了、没有计划',
    'dev.s12.r5f':'<code>/clear</code>，从 Phase 2 重新开始',
    'dev.s13.h': '十三、文件位置速查',
    'dev.s13.th.need': '需要',
    'dev.s13.th.where':'位置',
    'dev.s13.r1': '当前 Sprint 状态',
    'dev.s13.r2': '你的任务计划',
    'dev.s13.r3': '执行报告',
    'dev.s13.r4': '模板',
    'dev.s13.r5': '完整简报',
    'dev.s13.r6': '知识库',
    'dev.s13.r7': '自动加载的角色规则',
    'dev.s14.h': '十四、Claude 技能速查',
    'dev.s14.th.skill':'技能',
    'dev.s14.th.use':  '一句话用途',
    'dev.s14.th.phase':'阶段',
    'dev.s14.r1': '决定要做什么、按什么顺序做',
    'dev.s14.r2': '按已批准的计划执行',
    'dev.s14.r3': 'Go 代码规范与正确性检查',
    'dev.s14.r4': 'Kotlin / Android 代码检查',
    'dev.s14.r5': 'Flutter / Dart 代码检查',
    'dev.s14.r6': '按团队规范起草并推送提交',
    'dev.s14.r7': '把非显然的发现存入知识库',
    'dev.s14.r7p':'6（适用时）',
    'dev.s14.r8': '追加本 Sprint 的执行报告条目',
    'dev.s14.r8p':'6（每次）',
    'dev.summary':'<strong>要点总结：</strong>按 6 阶段顺序做事 · 一次一个技能 · 发现超范围就升级给 Lead · 任务之间 <code>/clear</code>。小事多 practice，大事自然顺。',
  },

  en: {
    /* ── Index page ── */
    'logo.tag':          'Internal',
    'hero.title':        'Team Internal Documentation Hub',
    'hero.sub':          'Product specs, QA handbooks, and project stories — all core docs in one place',
    'filter.all':        'All',
    'filter.prd':        'PRD',
    'filter.qa':         'QA',
    'filter.story':      'Story',
    'filter.dev':        'Dev',
    'filter.ba':         'BA',
    'filter.ops':        'Ops',
    'section.docs':      'Documents',
    'card.prd.title':    'Arrowfish VPN Business PRD',
    'card.prd.desc':     'Full product overview: user tiers, membership plans &amp; payments, VPN connection, marketing and content modules. Required reading for BA / PM.',
    'card.prd.audience': 'For: BA · PM · Non-technical members',
    'card.story.title':  'From Arrowfish to FFF — Product Evolution Story',
    'card.story.desc':   "Why we're rebuilding from scratch: Arrowfish's current state, limitations, FFF goals and timeline — helping everyone understand the product direction.",
    'card.story.audience':'For: All team members',
    'card.qa.title':     'QA Test Handbook — v3.7.0 Staging Config',
    'card.qa.desc':      'Staging baseline for v3.7.0 (current production): login rules, free duration, VPN connection behavior, versioning, payments, node sync, and common false-positive reference.',
    'card.qa.audience':  'For: QA Testers',
    'card.dev.title':    'Developer Onboarding — Claude Sprint Workflow',
    'card.dev.desc':     '6-phase per-task workflow (Claim → Plan → Execute → Verify → Commit → Close), Lead vs Dev role split, sprint-impact escalation, Claude skill cheat-sheet. Required reading for every developer.',
    'card.dev.audience': 'For: All developers',
    'card.ops.title':    'Node Operations Handbook — Lifecycle &amp; Automation',
    'card.ops.desc':     'End-to-end node lifecycle: health state machine, auto offline/recovery, DNS automation (GoDaddy + Cloudflare), one-click Quick Setup / Format, Telegram alert rules, deploy SOP.',
    'card.ops.audience': 'For: Developers · Operations',
    'card.ba.title':     'BA Business Handbook — Data · Flow · Admin',
    'card.ba.desc':      'User funnel, key metrics, paid plans &amp; dedicated-line workflow, refund &amp; support escalation, lottery / coupons mechanics, common admin actions. Quick reference for BA &amp; ops.',
    'card.ba.audience':  'For: BA · Operations · Customer Support',
    'card.read':         'Read Document',
    'footer':            'Arrowfish Team · Internal · Do Not Share · 2026',

    /* ── Doc page chrome ── */
    'doc.back':          'Back to Docs',
    'doc.toc.label':     'Contents',
    'doc.toc.toggle':    'Contents',

    /* ── PRD TOC ── */
    'prd.toc.s1':  '1. What Is The Product',
    'prd.toc.s2':  '2. Product Strategy',
    'prd.toc.s3':  '3. User System',
    'prd.toc.s4':  '4. Membership Plans',
    'prd.toc.s5':  '5. Payment Methods',
    'prd.toc.s6':  '6. VPN Connection',
    'prd.toc.s7':  '7. Free Trial &amp; Ads',
    'prd.toc.s8':  '8. Points &amp; Lottery',
    'prd.toc.s9':  '9. Referral &amp; Commission',
    'prd.toc.s10': '10. Coupons',
    'prd.toc.s11': '11. Marketing &amp; Campaigns',
    'prd.toc.s12': '12. Content Modules',
    'prd.toc.s13': '13. Feedback &amp; Support',
    'prd.toc.s14': '14. Notifications',
    'prd.toc.s15': '15. Admin Dashboard',
    'prd.toc.s16': '16. Compliance &amp; Privacy',
    'prd.toc.s17': '17. Business Metrics',

    /* ── Story TOC ── */
    'story.toc.s1': 'Background: What We Inherited',
    'story.toc.s2': 'Arrowfish: Current State',
    'story.toc.s3': 'Why FFF',
    'story.toc.s4': 'What Is FFF',
    'story.toc.s5': 'How Both Products Coexist',
    'story.toc.s6': 'Milestone Timeline',
    'story.toc.s7': 'What This Means for the Team',
    'story.toc.s8': 'Key Risks',

    /* ── QA TOC ── */
    'qa.toc.s1':  'Testing Environment Overview',
    'qa.toc.s2':  'Login &amp; Account Security',
    'qa.toc.s3':  'Free User Time Limits',
    'qa.toc.s4':  'VPN Connection Behavior (v3.6.x reconnect)',
    'qa.toc.s5':  'Client Version Control',
    'qa.toc.s6':  'System Feature Toggles',
    'qa.toc.s7':  'Ad Configuration',
    'qa.toc.s8':  'Payment Features (incl. IAP Renewal)',
    'qa.toc.s9':  'Node Sync (incl. Quick Setup / Format)',
    'qa.toc.s10': 'Common False Positives Reference',
    'qa.toc.s11': 'Known Issues List',
    'qa.toc.s12': 'Test Account Management',
    'qa.toc.s13': 'Staging vs Production Differences',
    'qa.toc.s14': 'Recent Releases (v3.7.0 / v3.2.0)',
    'qa.toc.s15': '4-Variant Download Portal QA Flow',

    /* ── BA TOC ── */
    'ba.toc.s1':  'User Funnel &amp; Key Metrics',
    'ba.toc.s2':  'Membership Plans &amp; Pricing',
    'ba.toc.s3':  'Dedicated Line / IP Workflow',
    'ba.toc.s4':  'Payment Channels &amp; Reconciliation',
    'ba.toc.s5':  'Refunds &amp; Support Escalation',
    'ba.toc.s6':  'Lottery · Coupons · Referral',
    'ba.toc.s7':  'Nodes &amp; Lines (Business View)',
    'ba.toc.s8':  'Common Admin Actions',
    'ba.toc.s9':  'Clients &amp; Frozen Versions',
    'ba.toc.s10': 'Glossary',

    /* ── Dev onboarding ── */
    'dev.badge':       'Developer',
    'dev.title':       'Developer Onboarding — Standard Claude Sprint Workflow',
    'dev.meta.audience':'For: All developers (new and experienced)',
    'dev.toc.s1':  '1. First-time Setup',
    'dev.toc.s2':  '2. Daily Start',
    'dev.toc.s3':  '3. The 6-Phase Task Loop',
    'dev.toc.s4':  '4. Phase 1 — Claim',
    'dev.toc.s5':  '5. Phase 2 — Plan',
    'dev.toc.s6':  '6. Phase 3 — Execute',
    'dev.toc.s7':  '7. Phase 4 — Verify',
    'dev.toc.s8':  '8. Phase 5 — Commit',
    'dev.toc.s9':  '9. Phase 6 — Close',
    'dev.toc.s10': '10. Lead vs Dev Roles',
    'dev.toc.s11': '11. Daily Iron Rules',
    'dev.toc.s12': '12. Trouble Handling',
    'dev.toc.s13': '13. File Locations',
    'dev.toc.s14': '14. Claude Skill Cheat-Sheet',
    'dev.toc.s15': '15. Detailed Walkthrough (each skill)',
    'dev.toc.s16': '16. Team Improvement Channel',
    'dev.intro':   'Every developer follows the same 6-phase loop for every task. Read it once, bookmark it, then run every task through this flow. The only way a small team can clone a standard set of moves is by following one shared playbook.',
    'dev.s1.h':  '1. First-time Setup (one-off)',
    'dev.s1.1':  'Clone the 5 team repos into <code>~/Documents/GitLab/skytree/</code>: <code>orebackend</code> · <code>proxy_android2</code> · <code>flutter_vpn</code> · <code>vpn-internal-reports</code> · <code>.vscode</code>',
    'dev.s1.2':  'Set Git identity: <code>git config --global user.name "&lt;your GitLab username&gt;"</code> + <code>git config --global user.email "&lt;your email&gt;"</code>',
    'dev.s1.3':  'Install Claude Code CLI, launch from the workspace root: <code>cd ~/Documents/GitLab/skytree &amp;&amp; claude</code>',
    'dev.s1.4':  'Run <code>/start</code> on first session — see project structure and current sprint status',
    'dev.s1.5':  'Read once: <code>vpn-internal-reports/team-workflow-briefing.md</code> (full briefing)',
    'dev.s2.h':  '2. Daily Start',
    'dev.s2.1':  '<code>git pull</code> in every repo',
    'dev.s2.2':  'Launch Claude from the workspace root',
    'dev.s2.3':  'Rename the session: <code>/rename "&lt;short task name&gt;"</code>',
    'dev.s2.4':  'Open <code>vpn-internal-reports/Sprint-&lt;N&gt;/README.md</code> for sprint status',
    'dev.s3.h':  '3. The 6-Phase Task Loop',
    'dev.s3.diagram': '┌──────────────────────────────────────────────────┐\n│  Each task = one 6-phase loop                    │\n├──────────────────────────────────────────────────┤\n│                                                  │\n│  1. CLAIM    — pick an unclaimed task from sprint│\n│                                                  │\n│  2. PLAN     — /plan  (study + design + impact check) │\n│                  ↳ over sprint capacity → escalate to Lead │\n│                                                  │\n│  3. EXECUTE  — /plan execute                     │\n│                                                  │\n│  4. VERIFY   — /go-specialist or /kotlin-specialist │\n│                (run once on the final diff)      │\n│                                                  │\n│  5. COMMIT   — /commit                           │\n│                                                  │\n│  6. CLOSE    — /knowledge-base-updater (if new finding)│\n│                /report update                    │\n│                /clear                            │\n│                                                  │\n└──────────────────────────────────────────────────┘',
    'dev.s4.h':  '4. Phase 1 — Claim',
    'dev.s4.1':  'In the Sprint README, find an unclaimed task that fits your priority and stack',
    'dev.s4.2':  'Set its <code>Owner</code> to your name and <code>Status</code> to <code>in-progress</code>',
    'dev.s4.3':  'Branch off <code>main</code> using prefixes from <code>rules/general/git.md</code>: <code>fea/</code> feature · <code>enh/</code> enhancement · <code>fix/</code> bugfix · <code>ref/</code> refactor · <code>hot/</code> hotfix',
    'dev.s4.4':  'Example: <code>fix/vpn-kill-switch-doze</code>',
    'dev.s5.h':  '5. Phase 2 — Plan',
    'dev.s5.1':  'Run <code>/plan</code> — enters plan mode',
    'dev.s5.2':  'Let Claude explore the code; answer its questions truthfully',
    'dev.s5.3':  'Copy <code>templates/task-plan.template.md</code> to <code>plans/&lt;branch-name&gt;.md</code>',
    'dev.s5.4':  'Fill in: background · acceptance criteria · approach · key files · risks · verification · out of scope · sprint impact',
    'dev.s5.escalate':'<strong>If sprint impact assessment says "over sprint capacity":</strong> add a <code>## SPRINT IMPACT</code> section to the plan with extra days needed + cut-queue candidate. <strong>Stop. Do not ExitPlanMode.</strong> Tell Lead in chat: <code>@lead sprint impact on Task #&lt;N&gt; — +&lt;X&gt;d. Cut-queue: Task #&lt;Y&gt;. Plan at vpn-internal-reports/plans/&lt;file&gt;.md</code>. Resume only after Lead decides — never silently expand scope.',
    'dev.s6.h':  '6. Phase 3 — Execute',
    'dev.s6.1':  'Run <code>/plan execute</code> — Claude works through the plan step by step',
    'dev.s6.2':  '<strong>Do not invoke other skills mid-execute</strong> — let <code>/plan execute</code> finish',
    'dev.s6.3':  'Anything unexpected → stop and ask Lead, do not silently change direction',
    'dev.s7.h':  '7. Phase 4 — Verify',
    'dev.s7.p':  'Run only after the diff is final and ready to commit.',
    'dev.s7.th.stack':'Stack',
    'dev.s7.th.skill':'Verification skill',
    'dev.s7.td.cross':'Cross-stack',
    'dev.s7.1':  'Fix issues raised by the specialist',
    'dev.s7.2':  '<strong>Specialist runs once</strong> — it is a checkpoint, not a chat tool',
    'dev.s8.h':  '8. Phase 5 — Commit',
    'dev.s8.1':  'Run <code>/commit</code>',
    'dev.s8.2':  'Review the drafted commit message — approve or adjust',
    'dev.s8.3':  'Title format: <code>Add | Fix | Update | Remove | Improve &lt;short description&gt;</code> (≤72 chars)',
    'dev.s8.4':  '<strong>Never</strong> use <code>--amend</code>, <code>--no-verify</code>, or <code>Co-Authored-By</code>',
    'dev.s8.5':  'Hook failed? Fix the root cause → create a <strong>new</strong> commit (do not amend)',
    'dev.s9.h':  '9. Phase 6 — Close',
    'dev.s9.1':  '<strong>Knowledge base</strong> (only for non-obvious findings): <code>/knowledge-base-updater "save: &lt;one-line finding&gt;"</code>. Skip for routine work.',
    'dev.s9.2':  '<strong>Execution report</strong> (every task): copy <code>templates/execution-report-entry.template.md</code> and append to <code>Sprint-&lt;N&gt;/execution-reports/phase-&lt;name&gt;.md</code>. Fill in: what shipped · non-obvious findings · follow-ups · sprint impact.',
    'dev.s9.3':  '<strong>Update Sprint README</strong>: set your task <code>Status</code> to <code>done</code>, commit to vpn-internal-reports.',
    'dev.s9.4':  'Open the MR in the product repo, assign Lead as reviewer.',
    'dev.s9.5':  '<code>/clear</code> — release context, task ends.',
    'dev.s10.h': '10. Lead vs Dev Roles',
    'dev.s10.th.action':'Action',
    'dev.s10.r1': 'Add task to sprint plan',
    'dev.s10.r1d':'❌ (request via chat)',
    'dev.s10.r2': 'Set priority / estimate days',
    'dev.s10.r3': 'Claim an unassigned task',
    'dev.s10.r3l':'✅ (if coding personally)',
    'dev.s10.r4': 'Fill in task plan (criteria/approach/risks)',
    'dev.s10.r5': 'Execute + commit + push',
    'dev.s10.r6': 'Decide cut-queue / postpone',
    'dev.s10.r6d':'❌ (escalate)',
    'dev.s10.r7': 'Review MR',
    'dev.s10.r8': 'Write execution-report entry',
    'dev.s10.r9': 'Update Sprint README status',
    'dev.s10.r9d':'✅ (own row only)',
    'dev.s11.h': '11. Daily Iron Rules (never break)',
    'dev.s11.1': '<strong>One skill at a time</strong> — never stack <code>/plan</code> + <code>/plan execute</code> + <code>/commit</code>',
    'dev.s11.2': '<strong>One session = one task</strong> — <code>/clear</code> between tasks',
    'dev.s11.3': '<strong>No silent scope expansion</strong> — if a task grows, escalate to Lead',
    'dev.s11.4': '<strong>Specialist only in Phase 4</strong> — not a "what do you think of my idea?" chat tool',
    'dev.s11.5': '<strong>Always use the templates</strong> — task-plan and execution-report; no freestyling',
    'dev.s11.6': '<strong>One task = one MR</strong> — merge only after Lead approves',
    'dev.s12.h': '12. Trouble Handling',
    'dev.s12.th.issue':'Situation',
    'dev.s12.th.fix':  'Action',
    'dev.s12.r1': 'Build fails',
    'dev.s12.r1f':'Fix in current session, re-run specialist; only commit when green',
    'dev.s12.r2': 'Commit hook blocks',
    'dev.s12.r2f':'Fix root cause, create a <strong>new</strong> commit, never use <code>--no-verify</code>',
    'dev.s12.r3': 'Merge conflicts',
    'dev.s12.r3f':'Resolve locally, re-run specialist on the resolved diff',
    'dev.s12.r4': 'New commits on remote',
    'dev.s12.r4f':'<code>git stash -u</code> → <code>git pull --ff-only</code> → <code>git stash pop</code> → rebuild',
    'dev.s12.r5': 'Session is messy, no plan',
    'dev.s12.r5f':'<code>/clear</code>, restart from Phase 2',
    'dev.s13.h': '13. File Locations',
    'dev.s13.th.need': 'Need',
    'dev.s13.th.where':'Location',
    'dev.s13.r1': 'Current sprint status',
    'dev.s13.r2': 'Your task plan',
    'dev.s13.r3': 'Execution reports',
    'dev.s13.r4': 'Templates',
    'dev.s13.r5': 'Full briefing',
    'dev.s13.r6': 'Knowledge base',
    'dev.s13.r7': 'Auto-loaded role rules',
    'dev.s14.h': '14. Claude Skill Cheat-Sheet',
    'dev.s14.th.skill':'Skill',
    'dev.s14.th.use':  'One-line use',
    'dev.s14.th.phase':'Phase',
    'dev.s14.r1': 'Decide what to do and in what order',
    'dev.s14.r2': 'Execute the approved plan',
    'dev.s14.r3': 'Go convention &amp; correctness check',
    'dev.s14.r4': 'Kotlin / Android code check',
    'dev.s14.r5': 'Flutter / Dart code check',
    'dev.s14.r6': 'Draft and push commit per team conventions',
    'dev.s14.r7': 'Save a non-obvious finding to the knowledge base',
    'dev.s14.r7p':'6 (when applicable)',
    'dev.s14.r8': 'Append an execution-report entry for this sprint',
    'dev.s14.r8p':'6 (every task)',
    'dev.summary':'<strong>Recap:</strong> follow the 6 phases in order · one skill at a time · escalate when scope blows up · <code>/clear</code> between tasks. Practice the small things; the big things follow.',
  }
};

function applyLang(lang) {
  const dict = T[lang] || T.zh;

  // Update html lang attribute
  document.documentElement.lang = lang === 'en' ? 'en' : 'zh-CN';

  // Apply all translations
  document.querySelectorAll('[data-i18n]').forEach(function(el) {
    var key = el.getAttribute('data-i18n');
    if (dict[key] !== undefined) {
      el.innerHTML = dict[key];
    }
  });

  // Toggle active state on lang buttons
  var btnZH = document.getElementById('btnZH');
  var btnEN = document.getElementById('btnEN');
  if (btnZH) btnZH.classList.toggle('active', lang === 'zh');
  if (btnEN) btnEN.classList.toggle('active', lang === 'en');

  // Delegate per-doc dates (and any other meta) to docs-meta.js if loaded
  if (typeof applyDocMeta === 'function') applyDocMeta(lang);
}

function initLang() {
  var lang = localStorage.getItem('aw_lang') || 'zh';
  applyLang(lang);
}

window.setLang = function(lang) {
  localStorage.setItem('aw_lang', lang);
  applyLang(lang);
};
